home:
  controller: 'App\Controller\MainController::home'
  path: '/'

experiences:
  controller: 'App\Controller\MainController::experiences'
  path: '/experiences'

studies:
  controller: 'App\Controller\MainController::studies'
  path: '/studies'

projects:
  controller: 'App\Controller\MainController::projects'
  path: '/projects'

resume:
  controller: 'App\Controller\MainController::resume'
  path: '/resume'
