index:
  controller: 'App\Controller\HomeController::index'
  path: '/'

experiences:
  controller: 'App\Controller\HomeController::experiences'
  path: '/experiences'

studies:
  controller: 'App\Controller\HomeController::studies'
  path: '/studies'

projects:
  controller: 'App\Controller\HomeController::studies'
  path: '/projects'

resume:
  controller: 'App\Controller\HomeController::resume'
  path: '/resume'
